apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: cloudacademy
spec:
 ingressClassName: nginx
 rules:
 - host: frontend.spcluster.tk
   http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service:
           name: frontend
           port: 
             number: 80