name: CI/CD for the voteapp-api into EKS cluster

on:
  push:
    branches:
      - master
    paths:
      - voteapp-api**
      - .github/workflows/backend.yml
    

jobs:
  build_and_deploy:
     runs-on: ubuntu-latest

     defaults:
       run:
         working-directory: voteapp-api

     steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: install dependencies
        run: go mod download

      - name: run build
        run: go build -o api
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.DOCKERPW }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./voteapp-api
          push: true
          tags: ghcr.io/${{ secrets.DOCKERUSER }}/voteapp-api:${{ github.run_number }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: update kube Config file
        run: aws eks update-kubeconfig --name my_cluster --region us-east-1

      - name: Deploy to EKS cluster
        env:
          imageTag: ghcr.io/${{ secrets.DOCKERUSER }}/voteapp-api:${{ github.run_number }}
        run: |
         kubectl set image deployment/api api=$imageTag -n cloudacademy
         

      
