name: CI/CD for the voteapp-frontend into EKS cluster

on:
  push:
    branches:
      - master
    paths:
      - voteapp-frontend-react/**
      - .github/workflows/frontend.yml
    

jobs:
  build_and_deploy:
     runs-on: ubuntu-latest

     defaults:
       run:
         working-directory: voteapp-frontend-react

     steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache dependencies of node-modules
        uses: actions/cache@v2
        with:
          path: voteapp-frontend-react/node_modules
          key: ${{ runner.os }}-npmcache-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npmcache-

      - name: install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm install --legacy-peer-deps

      - name: run build - react
        run: npm run build
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.DOCKERPW }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./voteapp-frontend-react
          push: true
          tags: ghcr.io/${{ secrets.DOCKERUSER }}/voteapp-frontend-react:${{ github.run_number }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: update kube Config file
        run: aws eks update-kubeconfig --name my_cluster --region us-east-1

      - name: Deploy to EKS cluster
        env:
          imageTag: ghcr.io/${{ secrets.DOCKERUSER }}/voteapp-frontend-react:${{ github.run_number }}
        run: |
         kubectl set image deployment/frontend-deploy frontend-image=$imageTag -n cloudacademy
         

      
